const langs = [
  "Magyar",
  "English (US)",
  "Deutsch",
  "Français (France)",
  "Italiano",
  "Русский",
  "Español",
  "Română",
  "Português (Brasil)",
  "العربية",
  "हिन्दी",
];

const others = [
  "Regisztráció",
  "Bejelentkezés",
  "Messenger",
  "Facebook Lite",
  "Watch",
  "Helyek",
  "Játékok",
  "Marketplace",
  "Meta Pay",
  "Oculus",
  "Portal",
  "Instagram",
  "Bulletin",
  "Helyi",
  "Adománygyűjtések",
  "Szolgáltatások",
  "Szavazási információs központ",
  "Csoportok",
  "Névjegy",
  "Hirdetés",
  "létrehozása",
  "Oldal létrehozása",
  "Fejlesztők",
  "Álláslehetőség",
  "Adatvédelem",
  "Cookie-k",
  "AdChoices",
  "Feltételek",
  "Súgó",
  "Névjegyzék feltöltése és nem felhasználók",
  "Beállítások",
  "Tevékenységnapló",
];

export default {
  langs,
  others,
};
